version: '3'
services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - cyperf-network
    # Add healthcheck to ensure service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 3
    # Start Ollama and wait for it to be ready before pulling the model
    entrypoint: >
      /bin/sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull gemma:2b &&
        tail -f /dev/null
      "

volumes:
  ollama_data:
    name: ollama_data

networks:
  cyperf-network:
    external: true