version: '3.8'

services:
  # FastAPI service (your existing app)
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8000:8000"
    environment:
      - SERVER_IP=${SERVER_IP}
      - CLIENT_IP=${CLIENT_IP}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_KEY_PATH=${SSH_KEY_PATH}
      - SSH_PASSWORD=${SSH_PASSWORD}
    volumes:
      - ${SSH_KEY_HOST_PATH:-/dev/null}:${SSH_KEY_PATH:-/tmp/dummy_key}:ro
    command: ["fastapi"]
    networks:
      - cyperf-network

  # Flask Frontend service
  flask-frontend:
    build:
      context: ./cce_flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    user: "app"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - CYPERF_API_BASE_URL=http://${FASTAPI_HOST:-fastapi}:8000/api
      - CYPERF_API_TIMEOUT=30
      - DEFAULT_TEST_DURATION=60
      - DEFAULT_SNAPSHOT_INTERVAL=5
      - DEFAULT_SERVER_IP=${SERVER_IP:-127.0.0.1}
      - DEFAULT_CLIENT_IP=${CLIENT_IP:-127.0.0.1}
      - PORT=5000
    depends_on:
      - fastapi
    networks:
      - cyperf-network

  # MCP Server service (stdio)
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    environment:
      - SERVER_IP=${SERVER_IP}
      - CLIENT_IP=${CLIENT_IP}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_KEY_PATH=${SSH_KEY_PATH}
      - SSH_PASSWORD=${SSH_PASSWORD}
    volumes:
      - ${SSH_KEY_HOST_PATH:-/dev/null}:${SSH_KEY_PATH:-/tmp/dummy_key}:ro
    command: ["mcp"]
    depends_on:
      - fastapi
    stdin_open: true
    tty: true
    networks:
      - cyperf-network

  # MCP HTTP Server service (Streamable HTTP)
  mcp-sse-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8001:8001"
    environment:
      - SERVER_IP=${SERVER_IP}
      - CLIENT_IP=${CLIENT_IP}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_KEY_PATH=${SSH_KEY_PATH}
      - SSH_PASSWORD=${SSH_PASSWORD}
      - FASTAPI_BASE_URL=http://${FASTAPI_HOST:-fastapi}:8000
    volumes:
      - ${SSH_KEY_HOST_PATH:-/dev/null}:${SSH_KEY_PATH:-/tmp/dummy_key}:ro
    command: ["mcp-sse"]
    depends_on:
      - fastapi
    networks:
      - cyperf-network

networks:
  cyperf-network:
    driver: bridge
